### ISSUE TITLE
Cell padding for "O" marks

### ISSUE THREAD

**Issue by MadLittleMods** [Costava/Tic-Tac-Toe-Topnotch#1]
The "O" marks need some padding to match the "X" marks.

![](https://camo.githubusercontent.com/4a6b10873c98511e5f4656745e34d5a272724703/68747470733a2f2f692e696d6775722e636f6d2f69736b564958672e706e67)

**Comment by Costava** [comment]
'O' padding is now implemented in commit f238343.
![two](https://cloud.githubusercontent.com/assets/8085910/6568521/e61d04d6-c6a6-11e4-8af4-8d5e3673277f.png)
